### ISSUE TITLE
lumpy conda environment

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#109]
@mvdbeek , it seems that when lumpy installs, this is python-3.6 that is installed, which I did not notice before (I do not mean that it was not already like that).
```python-3.6.0-1 100% |###############################| Time: 0:00:06   3.06 MB/s```
Not sure that it explains the strange bug I am fighting with these days but anyway:
is there a mean to simply enforce the python version in the requirement (conda) on the tool xml form ?

Thanks for the tip

**Comment by mvdbeek** [comment]
This could be the same problem as https://github.com/galaxyproject/galaxy/issues/3299.
The root problem there is that the conda resolver in galaxy <= release_16.10 resolves each dependency one at a time, but sometimes package a puts a limitation on package b. But galaxy's conda resolver doesn't know about this and installs incompatible versions.
If your root conda environment uses python3 (a.k.a miniconda3), and you install numpy, you get the python3 version of numpy. Then you install lumpy, which is python2 only ... and you are in trouble.
We have fixed this in release_17.01, which will enter feature freeze this week and should be released very soon.

For now you can indeed fix the python version (but this is really discouraged strongly, because that breaks everything that is not conda (docker, env modules, manuals TS packages). For lumpy, it should be enough to change the version of numpy from `1.11.2` to `1.11.2=py27_0`. The `py27_0` is the build number, you can see the available ones by doing `conda search numpy`

**Comment by mvdbeek** [comment]
Or we can add numpy as a dependency on lumpy in bioconda (and also copy the read extraction script into the bin folder). The logic there is to use lumpy as in the example, you need numpy, so it should come with lumpy.

**Comment by drosofff** [comment]
Thanks @mvdbeek !
Changing the version of numpy from 1.11.2 to 1.11.2=py27_0 fixes the issue, as far as I can tell. I'll PR this soon
