### ISSUE TITLE
Jenkins test fails with a KeyError in script dictionnary

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#21]

**Comment by mvdbeek** [comment]
This is https://github.com/ARTbio/internals/issues/5

**Comment by mvdbeek** [comment]
And also we moved form bitbucket to github for the internals, therefore I have to adapt the tesing script.

**Comment by drosofff** [comment]
I would like an update on Jenkins testing

**Comment by mvdbeek** [comment]
It's my hackathon project

**Comment by drosofff** [comment]
This is exactly why I wish an update

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2015-11-15 19:42 GMT+01:00 Marius van den Beek <notifications@github.com>:

> It's my hackathon project
>
> On Sun, Nov 15, 2015, 7:31 PM Christophe Antoniewski <

**Comment by mvdbeek** [comment]
Well, the short summary is that we need to modularize the jenkins jobs, because we are testing both Pull Requests (only linting, because someone could write a malicious Pull Request) and the master branch (where we lint and test), and this interferes with the repository status that we link in the readme.md.
If we split the jobs, the status indication should be OK again.
It would be nice to be able to also test Pull Requests, but to do that we would face troubles with the automatic toolshed uploads (Mid-term I imagine spinning up a dockerized toolshed per PR).

Then minor things are that we need to manually clone the repo containing the test-script and the API keys, and this has be more robust.

For getting things back to work I am confident that the hackathon is sufficient.

**Comment by drosofff** [comment]
I need a scheme. A slide.

**Comment by mvdbeek** [comment]
Hmm, i prefer to do that after the hackathon when I know what will work in practice, unless you want work with me on this during the hackathon.

**Comment by mvdbeek** [comment]
Since we buried our jenkins for the moment, I'll close it.
